//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Deweloperska
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEADLINE
    {
        public DEADLINE()
        {
            this.ZLECENIAs = new HashSet<ZLECENIA>();
        }
    
        public decimal DL_ID { get; set; }
        public Nullable<decimal> ZLEC_ID { get; set; }
        public System.DateTime DL_DEADLINE { get; set; }
        public string DL_OPIS { get; set; }
    
        public virtual ZLECENIA ZLECENIA { get; set; }
        public virtual ICollection<ZLECENIA> ZLECENIAs { get; set; }
    }
}
