//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Deweloperska
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRONTENDOWCY
    {
        public FRONTENDOWCY()
        {
            this.STANOWISKOes = new HashSet<STANOWISKO>();
            this.ZESPOLies = new HashSet<ZESPOLY>();
        }
    
        public decimal FRTND_ { get; set; }
    
        public virtual ICollection<STANOWISKO> STANOWISKOes { get; set; }
        public virtual ICollection<ZESPOLY> ZESPOLies { get; set; }
    }
}
