//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Deweloperska
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class firma_deweloperskaEntities : DbContext
    {
        public firma_deweloperskaEntities()
            : base("name=firma_deweloperskaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BACKENDOWCY> BACKENDOWCies { get; set; }
        public DbSet<BAZODANOWCY> BAZODANOWCies { get; set; }
        public DbSet<DEADLINE> DEADLINEs { get; set; }
        public DbSet<FRONTENDOWCY> FRONTENDOWCies { get; set; }
        public DbSet<KIEROWNICY> KIEROWNICies { get; set; }
        public DbSet<PRACOWNICY> PRACOWNICies { get; set; }
        public DbSet<PRIORYTETY> PRIORYTETies { get; set; }
        public DbSet<PROJEKTANCI> PROJEKTANCIs { get; set; }
        public DbSet<PRZEZNACZENIE> PRZEZNACZENIEs { get; set; }
        public DbSet<SPRZET> SPRZETs { get; set; }
        public DbSet<STANOWISKO> STANOWISKOes { get; set; }
        public DbSet<TESTERZY> TESTERZies { get; set; }
        public DbSet<UMOWY> UMOWies { get; set; }
        public DbSet<WYDATKI> WYDATKIs { get; set; }
        public DbSet<ZESPOLY> ZESPOLies { get; set; }
        public DbSet<ZLECENIA> ZLECENIAs { get; set; }
        public DbSet<ZYSKI> ZYSKIs { get; set; }
    }
}
