//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Deweloperska
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIORYTETY
    {
        public PRIORYTETY()
        {
            this.ZLECENIAs = new HashSet<ZLECENIA>();
        }
    
        public decimal PRIO_ID { get; set; }
        public string PRIO_NAZWA { get; set; }
        public decimal PRIO_PREMIA_DLA_ZESPOLU { get; set; }
    
        public virtual ICollection<ZLECENIA> ZLECENIAs { get; set; }
    }
}
