//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Deweloperska
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRZEZNACZENIE
    {
        public decimal PRZEZ_ID { get; set; }
        public Nullable<decimal> WYD_ID { get; set; }
        public string PRZEZ_NAZWA { get; set; }
        public Nullable<decimal> PRZEZ_NUMER_SERYJNY { get; set; }
        public Nullable<System.DateTime> PRZEZ_AKTYWNA_DO { get; set; }
    
        public virtual WYDATKI WYDATKI { get; set; }
    }
}
