//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Deweloperska
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRZET
    {
        public SPRZET()
        {
            this.ZESPOLies = new HashSet<ZESPOLY>();
        }
    
        public decimal SPRZET_ID { get; set; }
        public string SRZET_NAZWA { get; set; }
        public int SPRZET_ILOSC { get; set; }
    
        public virtual ICollection<ZESPOLY> ZESPOLies { get; set; }
    }
}
