//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Deweloperska
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMOWY
    {
        public decimal UMOWA_ID { get; set; }
        public Nullable<decimal> PRAC_ID { get; set; }
        public decimal UMOWA_PENSJA { get; set; }
        public System.DateTime UMOWA_DO_KIEDY { get; set; }
        public System.DateTime UMOWA_OD_KIEDY { get; set; }
    
        public virtual PRACOWNICY PRACOWNICY { get; set; }
    }
}
