//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Deweloperska
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZESPOLY
    {
        public ZESPOLY()
        {
            this.ZLECENIAs = new HashSet<ZLECENIA>();
        }
    
        public decimal ZESP_ID { get; set; }
        public Nullable<decimal> KIER_ID { get; set; }
        public Nullable<decimal> SPRZET_ID { get; set; }
        public Nullable<decimal> FRTND_ { get; set; }
        public Nullable<decimal> BCKND_ID { get; set; }
        public Nullable<decimal> TST_ID { get; set; }
        public Nullable<decimal> DB_ID { get; set; }
        public Nullable<decimal> PROJ_ID { get; set; }
    
        public virtual BACKENDOWCY BACKENDOWCY { get; set; }
        public virtual BAZODANOWCY BAZODANOWCY { get; set; }
        public virtual FRONTENDOWCY FRONTENDOWCY { get; set; }
        public virtual KIEROWNICY KIEROWNICY { get; set; }
        public virtual PROJEKTANCI PROJEKTANCI { get; set; }
        public virtual SPRZET SPRZET { get; set; }
        public virtual TESTERZY TESTERZY { get; set; }
        public virtual ICollection<ZLECENIA> ZLECENIAs { get; set; }
    }
}
