//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Deweloperska
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZLECENIA
    {
        public ZLECENIA()
        {
            this.DEADLINEs = new HashSet<DEADLINE>();
            this.ZYSKIs = new HashSet<ZYSKI>();
        }
    
        public decimal ZLEC_ID { get; set; }
        public decimal DL_ID { get; set; }
        public Nullable<decimal> PRIO_ID { get; set; }
        public decimal ZESP_ID { get; set; }
        public System.DateTime ZLEC_ROZPOCZECIE { get; set; }
        public bool ZLEC_ZAKONCZONO { get; set; }
    
        public virtual ICollection<DEADLINE> DEADLINEs { get; set; }
        public virtual DEADLINE DEADLINE { get; set; }
        public virtual PRIORYTETY PRIORYTETY { get; set; }
        public virtual ZESPOLY ZESPOLY { get; set; }
        public virtual ICollection<ZYSKI> ZYSKIs { get; set; }
    }
}
