//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Deweloperska
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZYSKI
    {
        public decimal ZYSK_ID { get; set; }
        public Nullable<decimal> ZLEC_ID { get; set; }
        public string ZYSK_UWAGI { get; set; }
    
        public virtual ZLECENIA ZLECENIA { get; set; }
    }
}
